Taking out models dependency on User Struct
RedHatInsights/export-service-go pull request #56
Opened 2023-03-06 15:53 UTC by dscervantes

- Taking out dependency of models User and creating a new User struct in Middleware. 
- [RHCLOUD-21483](https://issues.redhat.com/browse/RHCLOUD-21483)
Part two :Taking out models URL Params will be in a different PR

2023-03-06 20:24 UTC, CodyWMitchell approved these changes
LGTM!

2023-03-07 15:22 UTC, dehort requested changes
Looking good!!

I left a couple of comments/suggestions.

2023-03-07 15:22 UTC, dehort commented on middleware/user.go
> +	//"github.com/redhatinsights/export-service-go/models"
Please remove this line.

2023-03-07 15:22 UTC, dehort commented on exports/exports.go
> +func SwitchUser(user middleware.User) models.User {
What do you think about renaming this method to something like `mapUserToModelsUser()`.  I know its long-winded, but I think it communicates its purpose a little better.

Also, capitalizing the first letter exports the method outside of the package.  I do not think we need to export this method outside of the package at the moment.

2023-03-07 17:22 UTC, CodyWMitchell submitted a review, later dismissed

2023-03-07 21:54 UTC, dehort approved these changes
LGTM!

2023-03-08 19:57 UTC, merged